### ISSUE TITLE
minting error

### ISSUE THREAD

**Issue by Anil-akb** [jinglescode/emurgo-build-mesh-workshop#1]
[BrowserWallet] An error occurred during signTx: {"code":1,"info":"User has accepted the transaction sign, but the wallet was unable to sign the transaction (e.g. not having some of the private keys)."}.

**Comment by jinglescode** [comment]
@Anil-akb 
yup. its fixed, can give it another try?

**Comment by Anil-akb** [comment]
Thank you now it's working..
